class_name Enums

enum CardCategory { ATTACK, DEFENSE, EVASION }

enum CardEffect { LOGIC, EMOTION, HEAL_LOGIC, HEAL_EMOTION, SHIELD, CANCEL, MIRROR, REFLECT, RANDOM, BURST }

enum GamePhase { COIN_FLIP, PLAYER_TURN, OPPONENT_TURN, RESOLVING, EVENT_CHECK, DRAW, VICTORY_CHECK, MATCH_OVER }

enum Advantage { NEUTRAL, ATTACKER, DEFENDER }

enum EventType { MEDITATION, HEATED_EXCHANGE, MIND_GAMES, CRITICAL_TURNING_POINT, FATIGUE }
